### ISSUE TITLE
Session002 seems to have an incorrect definition of the static trial segment

### ISSUE THREAD

**Issue by moorepants** [mechmotum/baby-vibration#4]
![session002](https://github.com/user-attachments/assets/9573b062-0bde-43a5-9bdb-2e9535f5ba54)

Notice that there are two segments defined and the first is called "static", yet it is associated with a period of motion.

**Comment by GabrieleDello** [comment]
It is a clear mistake. YOYO_2 only contained the test at Aula (rectangular concrete blocks). I confused in defining the segments

**Comment by moorepants** [comment]
Once it is corrected, you can close this issue.

**Comment by moorepants** [comment]
From the new file:

![image](https://github.com/user-attachments/assets/aac5dce1-70e6-40e4-9eed-01d5ee669285)

thanks
